from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence
import json
import os
import tempfile


_REPORT_SCHEMA = "missipy.source_candidate.operator_external_review_report.v1"
_BUNDLE_SCHEMA = "missipy.source_candidate.github_export_bundle.v1"


@dataclass(frozen=True)
class SourceCandidateOperatorExternalReviewFinding:
    severity: str
    code: str
    message: str

    def to_json_dict(self) -> dict[str, object]:
        return {
            "severity": self.severity,
            "code": self.code,
            "message": self.message,
        }


@dataclass(frozen=True)
class SourceCandidateOperatorExternalReviewReport:
    bundle_path: Path
    repository: str | None
    dry_run: bool
    mutation_allowed: bool
    operation_count: int
    artifact_count: int
    finding_count: int
    recommended_action: str
    findings: tuple[SourceCandidateOperatorExternalReviewFinding, ...]

    def to_json_dict(self) -> dict[str, object]:
        return {
            "schema": _REPORT_SCHEMA,
            "bundle_path": str(self.bundle_path),
            "repository": self.repository,
            "dry_run": self.dry_run,
            "mutation_allowed": self.mutation_allowed,
            "operation_count": self.operation_count,
            "artifact_count": self.artifact_count,
            "finding_count": self.finding_count,
            "recommended_action": self.recommended_action,
            "findings": [finding.to_json_dict() for finding in self.findings],
        }


def build_source_candidate_operator_external_review_report(
    bundle_path: Path,
) -> SourceCandidateOperatorExternalReviewReport:
    """Build an operator-facing report from a local GitHub export bundle.

    This report is read-only. It inspects local artifacts generated by earlier
    phases and gives the operator a compact decision summary.
    """

    manifest_path = bundle_path / "manifest.json"
    manifest = _read_json_object(manifest_path)
    if manifest.get("schema") != _BUNDLE_SCHEMA:
        raise ValueError("GitHub export bundle manifest schema mismatch")

    findings: list[SourceCandidateOperatorExternalReviewFinding] = []
    artifacts = _artifact_map(manifest)

    _require_artifact(artifacts, "external_projection_contract", findings)
    _require_artifact(artifacts, "github_projection_payload", findings)
    gate_artifact = _require_artifact(artifacts, "remote_mutation_gate", findings)
    adapter_artifact = _require_artifact(artifacts, "github_adapter_dry_run", findings)

    gate_payload = _read_artifact_payload(bundle_path, gate_artifact)
    adapter_payload = _read_artifact_payload(bundle_path, adapter_artifact)

    dry_run = bool(manifest.get("dry_run"))
    mutation_allowed = bool(manifest.get("mutation_allowed"))
    operation_count = _int(manifest.get("operation_count"), default=0)
    artifact_count = _int(manifest.get("artifact_count"), default=0)
    repository = _optional_string(manifest.get("repository"))

    if not dry_run:
        findings.append(
            _error("payload_not_dry_run", "export bundle is not marked as dry-run")
        )

    if operation_count <= 0:
        findings.append(
            _warning("no_operations", "export bundle contains no external operations")
        )

    findings.extend(_gate_findings(gate_payload))
    findings.extend(_adapter_findings(adapter_payload))

    recommended_action = _recommended_action(
        dry_run=dry_run,
        mutation_allowed=mutation_allowed,
        findings=tuple(findings),
    )

    return SourceCandidateOperatorExternalReviewReport(
        bundle_path=bundle_path,
        repository=repository,
        dry_run=dry_run,
        mutation_allowed=mutation_allowed,
        operation_count=operation_count,
        artifact_count=artifact_count,
        finding_count=len(findings),
        recommended_action=recommended_action,
        findings=tuple(findings),
    )


def write_source_candidate_operator_external_review_report(
    path: Path,
    report: SourceCandidateOperatorExternalReviewReport,
) -> Path:
    _atomic_write_json(path, report.to_json_dict())
    return path


def render_source_candidate_operator_external_review_report(
    report: SourceCandidateOperatorExternalReviewReport,
) -> str:
    status = "READY" if report.recommended_action == "operator_review" else "BLOCKED"
    lines = [
        f"operator external review: {status}",
        f"repository: {report.repository or '<none>'}",
        f"bundle: {report.bundle_path}",
        f"dry_run: {report.dry_run}",
        f"mutation_allowed: {report.mutation_allowed}",
        f"operations: {report.operation_count}",
        f"artifacts: {report.artifact_count}",
        f"recommended_action: {report.recommended_action}",
        f"findings: {report.finding_count}",
    ]
    for finding in report.findings:
        lines.append(f"- {finding.severity}:{finding.code}: {finding.message}")
    return "\n".join(lines)


def read_source_candidate_operator_external_review_report(path: Path) -> dict[str, Any]:
    payload = _read_json_object(path)
    if payload.get("schema") != _REPORT_SCHEMA:
        raise ValueError("operator external review report schema mismatch")
    return dict(payload)


def _artifact_map(manifest: Mapping[str, Any]) -> dict[str, Mapping[str, Any]]:
    raw_artifacts = manifest.get("artifacts")
    if not isinstance(raw_artifacts, Sequence) or isinstance(raw_artifacts, (str, bytes, bytearray)):
        raise ValueError("bundle manifest artifacts must be a list")

    artifacts: dict[str, Mapping[str, Any]] = {}
    for raw_artifact in raw_artifacts:
        if not isinstance(raw_artifact, Mapping):
            raise ValueError("bundle manifest artifact must be an object")
        role = _optional_string(raw_artifact.get("role"))
        if role is not None:
            artifacts[role] = raw_artifact
    return artifacts


def _require_artifact(
    artifacts: Mapping[str, Mapping[str, Any]],
    role: str,
    findings: list[SourceCandidateOperatorExternalReviewFinding],
) -> Mapping[str, Any] | None:
    artifact = artifacts.get(role)
    if artifact is None:
        findings.append(_error("missing_artifact", f"missing bundle artifact: {role}"))
        return None
    return artifact


def _read_artifact_payload(
    bundle_path: Path,
    artifact: Mapping[str, Any] | None,
) -> Mapping[str, Any]:
    if artifact is None:
        return {}
    path_value = _optional_string(artifact.get("path"))
    if path_value is None:
        return {}

    path = Path(path_value)
    if not path.is_absolute():
        path = bundle_path / path.name
    if not path.exists():
        return {}

    try:
        return _read_json_object(path)
    except (json.JSONDecodeError, ValueError):
        return {}


def _gate_findings(payload: Mapping[str, Any]) -> tuple[SourceCandidateOperatorExternalReviewFinding, ...]:
    findings: list[SourceCandidateOperatorExternalReviewFinding] = []
    if not payload:
        return (_error("gate_missing_or_unreadable", "remote mutation gate artifact is missing or unreadable"),)

    mutation_allowed = bool(payload.get("mutation_allowed"))
    if not mutation_allowed:
        findings.append(
            _warning("gate_not_passing", "remote mutation gate is not passing")
        )

    for issue in _issues(payload):
        code = _optional_string(issue.get("code")) or "gate_issue"
        message = _optional_string(issue.get("message")) or "remote mutation gate issue"
        severity = _optional_string(issue.get("severity")) or "warning"
        findings.append(SourceCandidateOperatorExternalReviewFinding(severity=severity, code=code, message=message))

    return tuple(findings)


def _adapter_findings(payload: Mapping[str, Any]) -> tuple[SourceCandidateOperatorExternalReviewFinding, ...]:
    if not payload:
        return (_error("adapter_missing_or_unreadable", "adapter dry-run artifact is missing or unreadable"),)

    gate = payload.get("gate")
    plan = payload.get("plan")
    findings: list[SourceCandidateOperatorExternalReviewFinding] = []

    if not isinstance(gate, Mapping):
        findings.append(_error("adapter_gate_missing", "adapter dry-run does not include gate result"))
    if not isinstance(plan, Mapping):
        findings.append(_error("adapter_plan_missing", "adapter dry-run does not include plan"))

    if isinstance(plan, Mapping) and bool(plan.get("remote_mutation")):
        findings.append(_error("adapter_plan_remote_mutation", "adapter plan is marked as remote mutation"))

    return tuple(findings)


def _issues(payload: Mapping[str, Any]) -> tuple[Mapping[str, Any], ...]:
    raw_issues = payload.get("issues")
    if not isinstance(raw_issues, Sequence) or isinstance(raw_issues, (str, bytes, bytearray)):
        return ()
    return tuple(item for item in raw_issues if isinstance(item, Mapping))


def _recommended_action(
    *,
    dry_run: bool,
    mutation_allowed: bool,
    findings: tuple[SourceCandidateOperatorExternalReviewFinding, ...],
) -> str:
    if not dry_run:
        return "stop_not_dry_run"
    if any(finding.severity == "error" for finding in findings):
        return "fix_errors"
    if not mutation_allowed:
        return "review_gate_blockers"
    return "operator_review"


def _read_json_object(path: Path) -> Mapping[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, Mapping):
        raise ValueError(f"JSON payload must be an object: {path}")
    return payload


def _optional_string(raw: object) -> str | None:
    if isinstance(raw, str) and raw.strip():
        return raw
    return None


def _int(raw: object, *, default: int) -> int:
    if isinstance(raw, int):
        return raw
    return default


def _error(code: str, message: str) -> SourceCandidateOperatorExternalReviewFinding:
    return SourceCandidateOperatorExternalReviewFinding(
        severity="error",
        code=code,
        message=message,
    )


def _warning(code: str, message: str) -> SourceCandidateOperatorExternalReviewFinding:
    return SourceCandidateOperatorExternalReviewFinding(
        severity="warning",
        code=code,
        message=message,
    )


def _atomic_write_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=str(path.parent),
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as handle:
        tmp_name = handle.name
        handle.write(text)
    os.replace(tmp_name, path)
